sudo: false
os:
  - linux
  - osx
language: node_js
node_js:
  - '9'
  - '8'
  - '7'
  - '5'
  - '10'
  - '6'
  - '0.12'
  - '4'
  - '0.10'
matrix:
    fast_finish: true
    allow_failures:
      - node_js: 'node'
      - node_js: '0.8'
dist: trusty
